#!/usr/bin/env python3
"""Turn the BIOS knob schema XML into a C array for BiosCfgOobDxe.

The DXE pushes this document to the BMC as SetPayload type 1, LZMA-compressed
in the legacy "alone" container (props 0x5D, i.e. lc=3 lp=0 pb=2) — the same
encoding the BMC's lzmaAloneDecode() expects and the same one the driver
currently in the flash uses.

Emits, alongside the bytes, the exact length and CRC32 the DXE quotes in
SetPayload's start-of-transfer header. Computing them here rather than at run
time keeps the firmware free of a CRC pass over 13 KB on every boot and, more
importantly, lets the DXE compare them against what the BMC reports it already
holds and skip the transfer entirely.

Deterministic: same XML in, byte-identical header out.

usage: gen-schema-header.py <knobs.xml> <BiosCfgOobSchema.h>
"""
import lzma
import sys
import zlib


def main():
    if len(sys.argv) != 3:
        sys.stderr.write(__doc__)
        return 1

    xml = open(sys.argv[1], "rb").read()
    if not xml.startswith(b"<?xml"):
        sys.stderr.write("%s does not look like the knob schema XML\n" % sys.argv[1])
        return 1

    # FORMAT_ALONE + FILTER_LZMA1 gives the .lzma header the BMC decodes:
    # props byte, 4-byte dict size, 8-byte uncompressed size.
    blob = lzma.compress(
        xml,
        format=lzma.FORMAT_ALONE,
        filters=[{"id": lzma.FILTER_LZMA1, "preset": 9, "lc": 3, "lp": 0, "pb": 2}],
    )
    crc = zlib.crc32(blob) & 0xFFFFFFFF

    rows = []
    for i in range(0, len(blob), 12):
        rows.append("  " + " ".join("0x%02X," % b for b in blob[i:i + 12]))

    with open(sys.argv[2], "w") as f:
        f.write(
            "/** @file\n"
            "  BIOS knob schema pushed as SetPayload type 1, LZMA \"alone\" encoded.\n\n"
            "  GENERATED by gen-schema-header.py from x570d4i2t-bios-knobs.xml.\n"
            "  DO NOT EDIT - edit the XML instead.\n\n"
            "  xml    %d bytes\n"
            "  lzma   %d bytes\n"
            "  crc32  0x%08X\n\n"
            "  Copyright (c) 2024, ASRockRack X570D4I-2T OpenBMC port.\n"
            "  SPDX-License-Identifier: BSD-2-Clause-Patent\n"
            "**/\n\n"
            "#ifndef BIOS_CFG_OOB_SCHEMA_H_\n"
            "#define BIOS_CFG_OOB_SCHEMA_H_\n\n"
            "#include <Uefi.h>\n\n"
            "#define BIOS_CFG_SCHEMA_XML_SIZE  %d\n\n"
            "STATIC CONST UINT32  mBiosCfgSchemaSize  = %d;\n"
            "STATIC CONST UINT32  mBiosCfgSchemaCrc32 = 0x%08XU;\n\n"
            "STATIC CONST UINT8  mBiosCfgSchema[%d] = {\n"
            % (len(xml), len(blob), crc, len(xml), len(blob), crc, len(blob))
        )
        f.write("\n".join(rows).rstrip(","))
        f.write("\n};\n\n#endif /* BIOS_CFG_OOB_SCHEMA_H_ */\n")

    sys.stderr.write(
        "gen-schema-header: %d B xml -> %d B lzma, crc32 0x%08X\n"
        % (len(xml), len(blob), crc)
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
